name: Build & Deploy
on:
  pull_request:
    branches: [master]
    types: [closed]
    # Only run the job when the pull request is merged
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Build project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build project
        uses: actions/download-artifact@v3
        with:
          name: build-files
